baseurl: '/'
permalink: pretty
title: 'Schmuck today'

logo:
  mobile: "images/logo/logo.png"
  mobile_height: "98px"
  mobile_width: "117px"
  desktop: "images/logo/logo.png"
  desktop_height: "98px"
  desktop_width: "117px"

home: 
  limit_services: 6

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
